apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
stringData:
  aws_access_key_id: "<TU_ACCESS_KEY_ID>"
  aws_secret_access_key: "<TU_SECRET_ACCESS_KEY>"
  aws_session_token: "<TU_SESSION_TOKEN>"
