groups:
  - name: trafico
    interval: 30s
    rules:
      - record: api:http_server:rps
        expr: sum(rate(http_server_duration_count[1m]))
      - record: api:http_server:rps_by_code
        expr: sum by (http_response_status_code) (rate(http_server_duration_count[1m]))
      - record: api:http_server:rps_by_route
        expr: sum by (http_route) (rate(http_server_duration_count[1m]))

  - name: latencia
    interval: 30s
    rules:
      - record: api:http_server:latency:p95
        expr: histogram_quantile(0.95, sum by (le) (rate(http_server_duration_bucket[5m])))
      - record: api:http_server:latency:p99
        expr: histogram_quantile(0.99, sum by (le) (rate(http_server_duration_bucket[5m])))
      - record: api:http_server:latency:avg
        expr: sum(rate(http_server_duration_sum[5m])) / sum(rate(http_server_duration_count[5m]))

  - name: errores
    interval: 30s
    rules:
      - record: api:http_server:error_rate_5xx_percent
        expr: 100 * sum(rate(http_server_duration_count{http_response_status_code=~"5.."}[5m])) / sum(rate(http_server_duration_count[5m]))
      - record: api:http_server:error_rate_4xx_percent
        expr: 100 * sum(rate(http_server_duration_count{http_response_status_code=~"4.."}[5m])) / sum(rate(http_server_duration_count[5m]))

  - name: concurrencia
    interval: 30s
    rules:
      - record: api:http_server:active_requests
        expr: sum(http_server_active_requests)
